### ISSUE TITLE
Saját lokáció

### ISSUE THREAD

**Issue by VicziTomi** [flowacademyhu/kappa-meteo#15]
Az alkalmazás (böngésző) kéredezzen rá a user-nél a helyadatok használatára, célszerűen a főoldalon. Amennyiben ez jóváhagyásra kerül a felhasználó által, úgy kezelje az alkalmazás és a térképen jelenjen meg egy marker a user saját helyével.
A térképes zoom automatikusan állítódjon be egy olyan értékre, mellyel a saját pozícióhoz legközelebbi 3 állomás is megjelenítésre kerül.

**Comment by VicziTomi** [comment]
Ezt most nem kell megvalósítani, majd később:
A térképes zoom automatikusan állítódjon be egy olyan értékre, mellyel a saját pozícióhoz legközelebbi 3 állomás is megjelenítésre kerül.

**Comment by Andras92** [comment]
reviewed by @fixo91
