### ISSUE TITLE
Chart

### ISSUE THREAD

**Issue by VicziTomi** [flowacademyhu/kappa-meteo#18]
Felhasználónként, külön oldalon meg szeretném tekinteni a (megadott) időszakra vonatkozó mért értékeket, grafikusan. Ezeket egy-egy diagramon szükséges ábrázolni.
Be szeretném állítani, hogy mely időpontra, időszakra vonatkozó adatokat jelenítsen meg a chart.

- [x] dátum, időpont választó bevezetése a dashboard-ra
- [x] a beállított időpont szerinti backend hívás ezzel a paraméterrel
- [x] backend-en az időpont paraméter fogadása, feldolgozása, resopne előállítása
- [x] frontenden a kapott backend válasz szerint a választott időpontra érvényes adatok megjelenítése

Out of scope:
- szép design
- chart típus és kategória összerendelés

**Comment by Godfrid** [comment]
Sracok ez igy nagyon broad story. Rengeteg chart van es egyik masik configuralasa eleg komplex tud lenni. Mondtam bent is, tuzzetek ki realis celokat. Elso korben csinaljatok egy line chartot, es egy bar chartot, vagy gauge chartot, valami jol megfoghato hatarertekekkel rendelkezo adatra.
Ha ez megvan latni fogjatok kb hogy mukodnek es milyen adatigenyuk van lehet oket generalizalni tobb adatra, es ujabbakat kesziteni, esetleg tobb series megjeleniteni egy charton. Nem tartom valoszinunek hogy egy kombinalt tobb axisos line chart kivitelezese belefer az idobe.  @VicziTomi javaslom probaljatok meg a fentiek figyelembevetelevel par kezzelfoghatobb celt a chartok tekinteteben.

**Comment by VicziTomi** [comment]
FIX időszak lekérdezés a fókusz, tényleges funkcionalitás másik issue-n készül
